# Generated by Django 3.2.6 on 2021-09-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_auto_20210829_1637'),
        ('comment', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_answer.answer'),
            preserve_default=False,
        ),
    ]
